variable "env" {}
variable "subnet_ids" {}
variable "node_groups" {}
variable "eks_version" {}
variable "add_ons" {}
variable "eks-iam-access" {}
variable "vpc_id" {}
variable "kms_arn" {}
variable "zone_id" {}
variable "vpc_cidr" {}
variable "default_vpc_cidr" {}
