controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "classic"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:633788536644:certificate/764c1d94-5562-48f4-be92-fca22568f53d
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      http:
        port: 80
        targetPort: 80
      https:
        port: 443
        targetPort: 443