grafana:
  ingress:
    enabled: true
    ingressClassName: alb
    path: /*
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: roboshop
      alb.ingress.kubernetes.io/healthcheck-path: /login

prometheus:
  ingress:
    enabled: true
    ingressClassName: alb
    path: /*
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: roboshop
      alb.ingress.kubernetes.io/healthcheck-path: /graph

