name: Provision Roboshop Infrastructure
on: [workflow_dispatch]
jobs:
  DEV-PLAN:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Plan
        run: terraform plan -var-file=env-dev/main.tfvars

  DEV-APPLY:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=env-dev/main.tfvars -auto-approve

  QA:
    runs-on: ubuntu-latest
    needs: DEV-APPLY
    steps:
      - run: echo Just a Dummy Job

  UAT:
    runs-on: ubuntu-latest
    needs: QA
    steps:
      - run: echo Just a Dummy Job

  PROD:
    runs-on: self-hosted
    needs: UAT
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-prod/state.tfvars

