name: Provision Roboshop Infrastructure
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars

  QA:
    runs-on: ubuntu-latest
    needs: DEV
    steps:
      - run: echo Just a Dummy Job

  UAT:
    runs-on: ubuntu-latest
    needs: QA
    steps:
      - run: echo Just a Dummy Job

  PROD:
    runs-on: self-hosted
    needs: UAT
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-prod/state.tfvars

